kind: pipeline
type: docker
name: main

steps:
- name: SomeTests
  image: hseeberger/scala-sbt:8u222_1.3.5_2.13.1
  commands:
  - sbt "testOnly FiveStage.SomeTests"

---
kind: pipeline
type: docker
name: another_pipeline

steps:
- name: Ping
  image: hseeberger/scala-sbt:8u222_1.3.5_2.13.1
  commands:
  - echo "$(hostname)" 

---
kind: pipeline
type: docker
name: final

steps:
- name: finish
  image: hseeberger/scala-sbt:8u222_1.3.5_2.13.1
  commands:
  - echo "bye" 




depends_on:
- main
- another_pipeline