kind: pipeline
type: docker
name: main

resources:
  request:
    cpu: 2000
    memory: 2GiB


steps:
- name: SomeTests
  image: phyzaitlu/sbt:debian_openj9
  commands:
  - sbt "testOnly FiveStage.SomeTests"

---
kind: pipeline
type: docker
name: another_pipeline


steps:
- name: Ping
  image: phyzaitlu/sbt:debian_openj9
  commands:
  - echo "$(hostname)" 

---
kind: pipeline
type: docker
name: final

steps:
- name: finish
  image: phyzaitlu/sbt:debian_openj9
  commands:
  - echo "bye" 




depends_on:
- main
- another_pipeline
