kind: pipeline
type: docker
name: main

steps:
- name: SomeTests
  image: phyzaitlu/jdk:dragonwell 
  commands:
  - sbt "testOnly FiveStage.SomeTests"

---
kind: pipeline
type: docker
name: another_pipeline

steps:
- name: Ping
  image: phyzaitlu/jdk:dragonwell
  commands:
  - echo "$(hostname)" 

---
kind: pipeline
type: docker
name: final

steps:
- name: finish
  image: phyzaitlu/jdk:dragonwell
  commands:
  - echo "bye" 




depends_on:
- main
- another_pipeline
