kind: pipeline
type: docker
name: compile

steps:
- name: SomeTests
  image: phyzaitlu/sbt:zulu 
  commands:
  - sbt "compile"



---
kind: pipeline
type: docker
name: another_pipeline

steps:
- name: Ping
  image: phyzaitlu/sbt:zulu
  commands:
  - echo "$(hostname)" 

---
kind: pipeline
type: docker
name: final

steps:
- name: test
  image: phyzaitlu/sbt:zulu
  commands:
  - sbt "testOnly FiveStage.SomeTests"

node:
  memory: 4GiB


depends_on:
- compile
- another_pipeline
